### ISSUE TITLE
Request to get Data folder

### ISSUE THREAD

**Issue by KerouacDlg** [engcang/exploration-algorithms#1]
You mentioned a Data folder in line 31 of the no_unreal_run_experiment.launch. 
`  <arg name="data_directory" default="/home/mason/Documents/Data"/> `
I found that you did not provide this folder. How can I obtain this folder and related data?

**Comment by engcang** [comment]
Hi @KerouacDlg 
That directory is used for eval_data_node.py node and where the recording ros bag data is saved.
Change the directory where you want to save the rosbag data!

Refer here - https://github.com/ethz-asl/mav_active_3d_planning/blob/master/active_3d_planning_app_reconstruction/launch/run_experiment.launch#L139-L156

**Comment by KerouacDlg** [comment]
Thanks a lot！
